language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm ci
  - npm run lerna-install-ci
  - npm run build

script:
  - npm run test
  - npm run lint-travis
  - npm run coverage-coveralls
  # - node ./dist/app.js colorize ./fixtures/grammar/syntax/javascript.tmLanguage.json ./fixtures/grammar/src/sample.js
