language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm install
  - npm run build

script:
  - npm run lint-travis
  - npm run travis-coverage
  - node ./dist/app.js colorize ./fixtures/grammar/syntax/javascript.tmLanguage.json ./fixtures/grammar/src/sample.js
